export const record = [
  {
    id: "1",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2318,
    swimmer1: "兵頭",
    swimmer2: "洋樹",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-17",
    meet: "国民体育大会",
  },
  {
    id: "2",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5142,
    swimmer1: "兵頭",
    swimmer2: "洋樹",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-16",
    meet: "国民体育大会",
  },
  {
    id: "3",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11591,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾高",
    place: "くろしおアリーナ",
    date: "2017-07-30",
    meet: "高知県選手権",
  },
  {
    id: "4",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 24192,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-17",
    meet: "国民体育大会",
  },
  {
    id: "5",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "800m",
    time: 51263,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知工業高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "6",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 96255,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知工業高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "7",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2735,
    swimmer1: "森",
    swimmer2: "圭祐",
    swimmer3: null,
    swimmer4: null,
    team: "中村高",
    place: "くろしおアリーナ",
    date: "2013-07-27",
    meet: "高知県選手権",
  },
  {
    id: "8",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 5828,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南高",
    place: "くろしおアリーナ",
    date: "2009-07-19",
    meet: "四国高校選手権",
  },
  {
    id: "9",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 12598,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南高",
    place: "くろしおアリーナ",
    date: "2009-07-18",
    meet: "四国高校選手権",
  },
  {
    id: "10",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 2949,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "山口きらら博記念公園",
    date: "2020-02-09",
    meet: "きららカップ",
  },
  {
    id: "11",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6416,
    swimmer1: "田渕",
    swimmer2: "寛大",
    swimmer3: null,
    swimmer4: null,
    team: "鹿屋体育大",
    place: "くろしおアリーナ",
    date: "2016-07-31",
    meet: "高知県選手権",
  },
  {
    id: "12",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13740,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2019-08-25",
    meet: "全国JOC夏季",
  },
  {
    id: "13",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2489,
    swimmer1: "兵頭",
    swimmer2: "洋樹",
    swimmer3: null,
    swimmer4: null,
    team: "国士舘大",
    place: "くろしおアリーナ",
    date: "2012-07-29",
    meet: "高知県選手権",
  },
  {
    id: "14",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5415,
    swimmer1: "本田",
    swimmer2: "翔規",
    swimmer3: null,
    swimmer4: null,
    team: "国士舘大",
    place: "くろしおアリーナ",
    date: "2021-07-31",
    meet: "高知県選手権",
  },
  {
    id: "15",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 12133,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "法政大",
    place: "くろしおアリーナ",
    date: "2006-07-30",
    meet: "高知県選手権",
  },
  {
    id: "16",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12446,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業",
    place: "高茨城県笠松運動公園",
    date: "2002-08-17",
    meet: "日本高校選手権",
  },
  {
    id: "17",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 26327,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "くろしおアリーナ",
    date: "2002-09-22",
    meet: "国民体育大会",
  },
  {
    id: "18",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 9657,
    swimmer1: "西山",
    swimmer2: "中村",
    swimmer3: "堤",
    swimmer4: "川村",
    team: "高知県",
    place: "くろしおアリーナ",
    date: "2002-09-23",
    meet: "国民体育大会",
  },
  {
    id: "19",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 21808,
    swimmer1: "櫛田",
    swimmer2: "池本",
    swimmer3: "安岡",
    swimmer4: "坂本",
    team: "高知商業高",
    place: "くろしおアリーナ",
    date: "2020-07-19",
    meet: "高知県高校選手権",
  },
  {
    id: "20",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×200m",
    time: 48174,
    swimmer1: "西山",
    swimmer2: "安原",
    swimmer3: "濵田",
    swimmer4: "本田",
    team: "高知高",
    place: "アクアパレットまつやま",
    date: "2018-07-15",
    meet: "四国高校選手権",
  },
  {
    id: "21",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 11066,
    swimmer1: "藤澤",
    swimmer2: "笹岡",
    swimmer3: "中村",
    swimmer4: "堤",
    team: "高知県",
    place: "くろしおアリーナ",
    date: "2012-10-21",
    meet: "日本スポーツマスターズ",
  },
  {
    id: "22",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 23465,
    swimmer1: "稲田",
    swimmer2: "笹岡",
    swimmer3: "西山",
    swimmer4: "中村",
    team: "高知県",
    place: "宮城県総合運動公園",
    date: "2001-09-09",
    meet: "国民体育大会",
  },
  {
    id: "23",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2667,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "千葉県国際総合水泳場",
    date: "2010-09-12",
    meet: "国民体育大会",
  },
  {
    id: "24",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5822,
    swimmer1: "夏伐",
    swimmer2: "里奈",
    swimmer3: null,
    swimmer4: null,
    team: "岡山大",
    place: "くろしおアリーナ",
    date: "2009-07-25",
    meet: "高知県選手権",
  },
  {
    id: "25",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12528,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2012-08-28",
    meet: "全国JOC夏季",
  },
  {
    id: "26",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 26263,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-17",
    meet: "国民体育大会",
  },
  {
    id: "27",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 54634,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知高",
    place: "くろしおアリーナ",
    date: "2012-07-29",
    meet: "高知県選手権",
  },
  {
    id: "28",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2929,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "土佐高",
    place: "くろしおアリーナ",
    date: "2012-07-28",
    meet: "高知県選手権",
  },
  {
    id: "29",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6370,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "土佐高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "30",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13756,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾高",
    place: "島根県立水泳プール",
    date: "2004-08-19",
    meet: "日本高校選手権",
  },
  {
    id: "31",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3345,
    swimmer1: "中城",
    swimmer2: "実弓",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2008-06-22",
    meet: "高知県SC選手権",
  },
  {
    id: "32",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7145,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "近畿大学",
    place: "丸善インテックス大阪",
    date: "2021-08-29",
    meet: "関西学生夏季長水",
  },
  {
    id: "33",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 14893,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "近畿大学",
    place: "浜名市総合水泳場ToBio",
    date: "2022-01-30",
    meet: "浜名湾長水路選手権",
  },
  {
    id: "34",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2802,
    swimmer1: "矢部",
    swimmer2: "瀬里香",
    swimmer3: null,
    swimmer4: null,
    team: "高知追手前高",
    place: "くろしおアリーナ",
    date: "2019-09-08",
    meet: "高知県学年別",
  },
  {
    id: "35",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6247,
    swimmer1: "森本",
    swimmer2: "里華",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "児島地区公園水泳場",
    date: "2005-09-12",
    meet: "国民体育大会",
  },
  {
    id: "36",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 13452,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2001-08-29",
    meet: "全国JOC夏季",
  },
  {
    id: "37",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 13978,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "香長中",
    place: "くろしおアリーナ",
    date: "2016-07-24",
    meet: "高知県中学校",
  },
  {
    id: "38",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 29116,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "アクアパレットまつやま",
    date: "2018-07-14",
    meet: "四国高校選手権",
  },
  {
    id: "39",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11129,
    swimmer1: "植野美",
    swimmer2: "植野希",
    swimmer3: "阿佐",
    swimmer4: "北川",
    team: "高知県",
    place: "くろしおアリーナ",
    date: "2002-09-23",
    meet: "国民体育大会",
  },
  {
    id: "40",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 24052,
    swimmer1: "早本",
    swimmer2: "佐々木",
    swimmer3: "楠瀬",
    swimmer4: "山岡",
    team: "高知県",
    place: "山口きらら博記念公園",
    date: "2011-09-09",
    meet: "国民体育大会",
  },
  {
    id: "41",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×200m",
    time: 52672,
    swimmer1: "岩瀬",
    swimmer2: "佐古田",
    swimmer3: "平",
    swimmer4: "山下",
    team: "高知商業高",
    place: "アクアパレットまつやま",
    date: "2021-07-18",
    meet: "四国高校選手権",
  },
  {
    id: "42",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12924,
    swimmer1: "梅原",
    swimmer2: "山本",
    swimmer3: "博田",
    swimmer4: "西山",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-06-28",
    meet: "高知県SC選手権",
  },
  {
    id: "43",
    category: "高知県記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 26299,
    swimmer1: "山下",
    swimmer2: "西ノ内",
    swimmer3: "前野",
    swimmer4: "岩瀬",
    team: "ZEYO-ST",
    place: "東和薬品ラクタブドーム",
    date: "2021-08-26",
    meet: "全国JOC夏季",
  },
  {
    id: "44",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2618,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-29",
    meet: "四国学童選手権",
  },
  {
    id: "45",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5684,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-08",
    meet: "高知県学童選手権",
  },
  {
    id: "46",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 12802,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-08",
    meet: "高知県学童選手権",
  },
  {
    id: "47",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 27392,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-07-31",
    meet: "高知県選手権",
  },
  {
    id: "48",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "800m",
    time: 60775,
    swimmer1: null,
    swimmer2: null,
    swimmer3: null,
    swimmer4: null,
    team: null,
    place: null,
    date: null,
    meet: null,
  },
  {
    id: "49",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 111950,
    swimmer1: "下元",
    swimmer2: "規久",
    swimmer3: null,
    swimmer4: null,
    team: "ピープル高知",
    place: "高知市営プ",
    date: "1984-08-07",
    meet: "高知県選手権",
  },
  {
    id: "50",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 3116,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-06-27",
    meet: "高知県SC選手権",
  },
  {
    id: "51",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6779,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-08",
    meet: "高知県学童選手権",
  },
  {
    id: "52",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 15380,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-07-31",
    meet: "高知県選手権",
  },
  {
    id: "53",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3335,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-07-31",
    meet: "高知県選手権",
  },
  {
    id: "54",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7250,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-08",
    meet: "高知県学童選手権",
  },
  {
    id: "55",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 15602,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-07-31",
    meet: "高知県選手権",
  },
  {
    id: "56",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2731,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東和薬品ラクタブドーム",
    date: "2021-08-23",
    meet: "全国JOC夏季",
  },
  {
    id: "57",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 6256,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-06-27",
    meet: "高知県SC選手権",
  },
  {
    id: "58",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 14068,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "春野運動公園プ",
    date: "1996-07-28",
    meet: "高知県選手権",
  },
  {
    id: "59",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 13885,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-01",
    meet: "高知県選手権",
  },
  {
    id: "60",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 30856,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-06-27",
    meet: "高知県SC選手権",
  },
  {
    id: "61",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11644,
    swimmer1: "川田",
    swimmer2: "三善",
    swimmer3: "古谷",
    swimmer4: "佐藤",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-29",
    meet: "四国学童選手権",
  },
  {
    id: "62",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12906,
    swimmer1: "佐藤",
    swimmer2: "川田",
    swimmer3: "三善",
    swimmer4: "柳川",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-08-29",
    meet: "四国学童選手権",
  },
  {
    id: "63",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2813,
    swimmer1: "松井",
    swimmer2: "遥南",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "山口きらら博記念公園",
    date: "2020-02-09",
    meet: "きららカップ",
  },
  {
    id: "64",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 6219,
    swimmer1: "松井",
    swimmer2: "遥南",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2019-08-24",
    meet: "四国学童選手権",
  },
  {
    id: "65",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 13728,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2011-06-26",
    meet: "高知県SC選手権",
  },
  {
    id: "66",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 28699,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "春野運動公園プ",
    date: "1999-09-05",
    meet: "高知県秋季ジュニア",
  },
  {
    id: "67",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 60775,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "春野運動公園プ",
    date: "1999-09-05",
    meet: "高知県秋季ジュニア",
  },
  {
    id: "68",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 3124,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2006-08-27",
    meet: "全国JOC夏季",
  },
  {
    id: "69",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6713,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "秋田県立総合プール",
    date: "2006-10-09",
    meet: "JSCAブロック対抗",
  },
  {
    id: "70",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 14685,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2006-09-18",
    meet: "高知県秋季ジュニア",
  },
  {
    id: "71",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3476,
    swimmer1: "栗山",
    swimmer2: "陽菜",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "山口きらら博記念公園",
    date: "2020-02-09",
    meet: "きららカップ",
  },
  {
    id: "72",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7538,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "山口きらら博記念公園",
    date: "2013-10-06",
    meet: "JSCAブロック対抗",
  },
  {
    id: "73",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 16405,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2013-07-27",
    meet: "高知県選手権",
  },
  {
    id: "74",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 3028,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2011-08-21",
    meet: "四国学童選手権",
  },
  {
    id: "75",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6644,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2011-08-26",
    meet: "全国JOC夏季",
  },
  {
    id: "76",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 14489,
    swimmer1: "前野",
    swimmer2: "希和",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "三重交通Gスポーツの杜鈴鹿",
    date: "2016-03-12",
    meet: "朝日新聞社オール学童",
  },
  {
    id: "77",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 14650,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "東京辰巳国際水泳場",
    date: "2013-08-26",
    meet: "全国JOC夏季",
  },
  {
    id: "78",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 30739,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2013-09-08",
    meet: "高知県秋季ジュニア",
  },
  {
    id: "79",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11971,
    swimmer1: "前野",
    swimmer2: "西ノ内",
    swimmer3: "野中",
    swimmer4: "秋森",
    team: "ZEYO-ST",
    place: "三重交通Gスポーツの杜鈴鹿",
    date: "2016-03-13",
    meet: "朝日新聞社オール学童",
  },
  {
    id: "80",
    category: "高知県学童記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 13045,
    swimmer1: "前野",
    swimmer2: "野中",
    swimmer3: "秋森",
    swimmer4: "西ノ内",
    team: "ZEYO-ST",
    place: "三重交通Gスポーツの杜鈴鹿",
    date: "2016-03-13",
    meet: "朝日新聞社オール学童",
  },
  {
    id: "81",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2505,
    swimmer1: "中村",
    swimmer2: "真司",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "春野運動公園プ",
    date: "1996-07-22",
    meet: "高知県中学選手権",
  },
  {
    id: "82",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5438,
    swimmer1: "坂本",
    swimmer2: "昂太",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2018-07-28",
    meet: "高知県選手権",
  },
  {
    id: "83",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11985,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "ダイエープロビスフェニックス",
    date: "2009-10-17",
    meet: "JSCAブロック対抗",
  },
  {
    id: "84",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 25111,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "夜須中",
    place: "福岡県立総合プール",
    date: "2009-08-23",
    meet: "全国中学校",
  },
  {
    id: "85",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "800m",
    time: 52052,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "夜須中",
    place: "福岡県立総合プール",
    date: "2009-08-21",
    meet: "全国中学校",
  },
  {
    id: "86",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 98347,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "夜須中",
    place: "福岡県立総合プール",
    date: "2009-08-21",
    meet: "全国中学校",
  },
  {
    id: "87",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2906,
    swimmer1: "稲田",
    swimmer2: "康宏",
    swimmer3: null,
    swimmer4: null,
    team: "ピープル高知",
    place: "春野運動公園プ",
    date: "1993-08-01",
    meet: "高知県選手権",
  },
  {
    id: "88",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6160,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南中",
    place: "くろしおアリーナ",
    date: "2006-08-21",
    meet: "全国中学校",
  },
  {
    id: "89",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13212,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南中",
    place: "くろしおアリーナ",
    date: "2006-08-22",
    meet: "全国中学校",
  },
  {
    id: "90",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3047,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "JAPAN",
    place: "OCBCアクアティックセンター",
    date: "2018-03-16",
    meet: "シンガポールエージ選手権",
  },
  {
    id: "91",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6503,
    swimmer1: "5安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "くろしおアリーナ",
    date: "2017-07-30",
    meet: "高知県選手権",
  },
  {
    id: "92",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13953,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "鴨池公園水泳プール",
    date: "2017-08-18",
    meet: "全国中学校",
  },
  {
    id: "93",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13953,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "OCBCアクアティックセンター",
    date: "2018-03-15",
    meet: "シンガポールエージ選手権",
  },
  {
    id: "94",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2604,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "県立中村中",
    place: "くろしおアリーナ",
    date: "2014-07-27",
    meet: "高知県選手権",
  },
  {
    id: "95",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5678,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "県立中村中",
    place: "くろしおアリーナ",
    date: "2014-08-23",
    meet: "全国中学校",
  },
  {
    id: "96",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 12843,
    swimmer1: "津江",
    swimmer2: "透仁",
    swimmer3: null,
    swimmer4: null,
    team: "高知城北中",
    place: "くろしおアリーナ",
    date: "2018-09-09",
    meet: "高知県学年別",
  },
  {
    id: "97",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12940,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "城北中",
    place: "長野市アクアウイング",
    date: "1999-08-23",
    meet: "全国中学校",
  },
  {
    id: "98",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 27286,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "城北中",
    place: "長野市アクアウイング",
    date: "1999-08-22",
    meet: "全国中学校",
  },
  {
    id: "99",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11696,
    swimmer1: "大田",
    swimmer2: "井上",
    swimmer3: "末松",
    swimmer4: "西本",
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2018-06-24",
    meet: "高知県SC選手権",
  },
  {
    id: "100",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 23054,
    swimmer1: "松田",
    swimmer2: "窪川",
    swimmer3: "吉名",
    swimmer4: "安原",
    team: "高知中",
    place: "くろしおアリーナ",
    date: "2021-07-25",
    meet: "高知県中学校",
  },
  {
    id: "101",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 13217,
    swimmer1: "岩崎",
    swimmer2: "井上",
    swimmer3: "末松",
    swimmer4: "大田",
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2018-06-24",
    meet: "高知県SC選手権",
  },
  {
    id: "102",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 25230,
    swimmer1: "伊藤",
    swimmer2: "細川",
    swimmer3: "田海",
    swimmer4: "坂本",
    team: "高知南中",
    place: "くろしおアリーナ",
    date: "2006-08-22",
    meet: "全国中学校",
  },
  {
    id: "103",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2709,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "コナミ高知",
    place: "くろしおアリーナ",
    date: "2013-07-28",
    meet: "高知県選手権",
  },
  {
    id: "104",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5878,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "コナミ高知",
    place: "くろしおアリーナ",
    date: "2013-07-27",
    meet: "高知県選手権",
  },
  {
    id: "105",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12733,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "くろしおアリーナ",
    date: "2009-07-26",
    meet: "高知県選手権",
  },
  {
    id: "106",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 26762,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "福岡県立総合プール",
    date: "2009-08-23",
    meet: "全国中学校",
  },
  {
    id: "107",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 55640,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "ダイエープロビスフェニックス",
    date: "2009-10-17",
    meet: "JSCAブロック対抗",
  },
  {
    id: "108",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 3031,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2012-05-27",
    meet: "ジャパンオープン",
  },
  {
    id: "109",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6454,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2009-08-29",
    meet: "全国JOC夏季",
  },
  {
    id: "110",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13890,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "土佐中",
    place: "福岡県立総合プール",
    date: "2009-08-22",
    meet: "全国中学校",
  },
  {
    id: "111",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3390,
    swimmer1: "西ノ内",
    swimmer2: "春々",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2019-07-27",
    meet: "高知県選手権",
  },
  {
    id: "112",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7232,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2014-07-27",
    meet: "高知県選手権",
  },
  {
    id: "113",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 15131,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "香長中",
    place: "くろしおアリーナ",
    date: "2014-08-22",
    meet: "全国中学校",
  },
  {
    id: "114",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2862,
    swimmer1: "角岡",
    swimmer2: "爽土",
    swimmer3: null,
    swimmer4: null,
    team: "佐塾中",
    place: "くろしおアリーナ",
    date: "2015-07-26",
    meet: "高知県選手権",
  },
  {
    id: "115",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6338,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2012-08-27",
    meet: "全国JOC夏季",
  },
  {
    id: "116",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 13978,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "香長中",
    place: "くろしおアリーナ",
    date: "2016-07-24",
    meet: "高知県中学校",
  },
  {
    id: "117",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 13452,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2001-04-21",
    meet: "日本選手権",
  },
  {
    id: "118",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11878,
    swimmer1: "西山",
    swimmer2: "山本",
    swimmer3: "博田",
    swimmer4: "梅原",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-06-28",
    meet: "高知県SC選手権",
  },
  {
    id: "119",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 24911,
    swimmer1: "矢部",
    swimmer2: "佐古田",
    swimmer3: "秋森",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2017-06-25",
    meet: "高知県SC選手権",
  },
  {
    id: "120",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12924,
    swimmer1: "梅原",
    swimmer2: "山本",
    swimmer3: "博田",
    swimmer4: "西山",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-06-28",
    meet: "高知県SC選手権",
  },
  {
    id: "121",
    category: "高知県中学記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 26886,
    swimmer1: "矢部",
    swimmer2: "秋森",
    swimmer3: "前野",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2017-06-25",
    meet: "高知県SC選手権",
  },
  {
    id: "122",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2415,
    swimmer1: "山崎",
    swimmer2: "瑛士",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "123",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5261,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾高",
    place: "くろしおアリーナ",
    date: "2017-07-16",
    meet: "四国高校選手権",
  },
  {
    id: "124",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11591,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾高",
    place: "くろしおアリーナ",
    date: "2017-07-30",
    meet: "高知県選手権",
  },
  {
    id: "125",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 24192,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-17",
    meet: "国民体育大会",
  },
  {
    id: "126",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "800m",
    time: 51263,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知工業高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "127",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 96255,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知工業高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "128",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2735,
    swimmer1: "森",
    swimmer2: "圭祐",
    swimmer3: null,
    swimmer4: null,
    team: "中村高",
    place: "くろしおアリーナ",
    date: "2013-07-27",
    meet: "高知県選手権",
  },
  {
    id: "129",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 5828,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南高",
    place: "くろしおアリーナ",
    date: "2009-07-19",
    meet: "四国高校選手権",
  },
  {
    id: "130",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 12598,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "高知南高",
    place: "くろしおアリーナ",
    date: "2009-07-18",
    meet: "四国高校選手権",
  },
  {
    id: "131",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 2949,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "山口きらら博記念公園",
    date: "2020-02-09",
    meet: "きららカップ",
  },
  {
    id: "132",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6450,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "高知高",
    place: "くろしおアリーナ",
    date: "2020-09-13",
    meet: "高知県学年別",
  },
  {
    id: "133",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13740,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2019-08-25",
    meet: "全国JOC夏季",
  },
  {
    id: "134",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2510,
    swimmer1: "西山",
    swimmer2: "隆詞",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "春野運動公園プ",
    date: "1997-09-21",
    meet: "秋季ジュニア記録会",
  },
  {
    id: "135",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5548,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "中村高",
    place: "くろしおアリーナ",
    date: "2015-06-14",
    meet: "高知県高校選手権",
  },
  {
    id: "136",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 12246,
    swimmer1: "西内",
    swimmer2: "亘",
    swimmer3: null,
    swimmer4: null,
    team: "高知工業高",
    place: "くろしおアリーナ",
    date: "2012-09-09",
    meet: "高知県秋季ジュニア",
  },
  {
    id: "137",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12446,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "茨城県笠松運動公園",
    date: "2002-08-17",
    meet: "日本高校選手権",
  },
  {
    id: "138",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 26327,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "くろしおアリーナ",
    date: "2002-09-22",
    meet: "国民体育大会",
  },
  {
    id: "139",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 21808,
    swimmer1: "櫛田",
    swimmer2: "池本",
    swimmer3: "安岡",
    swimmer4: "坂本",
    team: "高知商業高",
    place: "くろしおアリーナ",
    date: "2020-07-19",
    meet: "高知県高校選手権",
  },
  {
    id: "140",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×200m",
    time: 48174,
    swimmer1: "西山",
    swimmer2: "安原",
    swimmer3: "濵田",
    swimmer4: "本田",
    team: "高知高",
    place: "アクアパレットまつやま",
    date: "2018-07-15",
    meet: "四国高校選手権",
  },
  {
    id: "141",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 23965,
    swimmer1: "本田",
    swimmer2: "安原",
    swimmer3: "西山",
    swimmer4: "濵田",
    team: "高知高",
    place: "アクアパレットまつやま",
    date: "2018-07-15",
    meet: "四国高校選手権",
  },
  {
    id: "142",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2667,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "千葉県国際総合水泳場",
    date: "2010-09-12",
    meet: "国民体育大会",
  },
  {
    id: "143",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5871,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "土佐女子高",
    place: "くろしおアリーナ",
    date: "2010-07-31",
    meet: "高知県選手権",
  },
  {
    id: "144",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12528,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2012-08-28",
    meet: "全国JOC夏季",
  },
  {
    id: "145",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 26263,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知県",
    place: "長良川スイミングプラザ",
    date: "2012-09-17",
    meet: "国民体育大会",
  },
  {
    id: "146",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "自由形",
    distance: "1500m",
    time: 54634,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "高知高",
    place: "くろしおアリーナ",
    date: "2012-07-29",
    meet: "高知県選手権",
  },
  {
    id: "147",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2929,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "土佐高",
    place: "くろしおアリーナ",
    date: "2012-07-28",
    meet: "高知県選手権",
  },
  {
    id: "148",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6370,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "土佐高",
    place: "ダイエープロビスフェニックス",
    date: "2012-08-18",
    meet: "日本高校選手権",
  },
  {
    id: "149",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13756,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾高校",
    place: "島根県立水泳プール",
    date: "2004-08-19",
    meet: "日本高校選手権",
  },
  {
    id: "150",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3345,
    swimmer1: "中城",
    swimmer2: "実弓",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2008-06-22",
    meet: "高知県SC選手権",
  },
  {
    id: "151",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7250,
    swimmer1: "中城",
    swimmer2: "実弓",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-06-28",
    meet: "高知県SC選手権",
  },
  {
    id: "152",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 15203,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "東京辰巳国際水泳場",
    date: "2019-08-25",
    meet: "全国JOC夏季",
  },
  {
    id: "153",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2802,
    swimmer1: "矢部",
    swimmer2: "瀬里香",
    swimmer3: null,
    swimmer4: null,
    team: "高知追手前高",
    place: "くろしおアリーナ",
    date: "2019-09-08",
    meet: "高知県学年別",
  },
  {
    id: "154",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6303,
    swimmer1: "吉岡",
    swimmer2: "まゆみ",
    swimmer3: null,
    swimmer4: null,
    team: "ピープル高知",
    place: "東京体育館室内プ",
    date: "1986-08-28",
    meet: "全国JO夏季",
  },
  {
    id: "155",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 13669,
    swimmer1: "前野",
    swimmer2: "希和",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "東和薬品ラクタブドーム",
    date: "2021-08-24",
    meet: "全国JOC夏季",
  },
  {
    id: "156",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 14034,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "くろしおアリーナ",
    date: "2019-09-08",
    meet: "高知県学年別",
  },
  {
    id: "157",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 29116,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知商業高",
    place: "アクアパレットまつやま",
    date: "2018-07-14",
    meet: "四国高校選手権",
  },
  {
    id: "158",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 24052,
    swimmer1: "早本",
    swimmer2: "佐々木",
    swimmer3: "楠瀬",
    swimmer4: "山岡",
    team: "高知県",
    place: "山口きらら博記念公園",
    date: "2011-09-09",
    meet: "国民体育大会",
  },
  {
    id: "159",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×200m",
    time: 52672,
    swimmer1: "岩瀬",
    swimmer2: "佐古田",
    swimmer3: "平",
    swimmer4: "山下",
    team: "高知商業高",
    place: "アクアパレットまつやま",
    date: "2021-07-18",
    meet: "四国高校選手権",
  },
  {
    id: "160",
    category: "高知県高校記録",
    poolsize: "長水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 26299,
    swimmer1: "山下",
    swimmer2: "西ノ内",
    swimmer3: "前野",
    swimmer4: "岩瀬",
    team: "ZEYO-ST",
    place: "東和薬品ラクタブドーム",
    date: "2021-08-26",
    meet: "全国JOC夏季",
  },
  {
    id: "161",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2317,
    swimmer1: "西山",
    swimmer2: "隆詞",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2021-02-21",
    meet: "高知県SC記録会",
  },
  {
    id: "162",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5094,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "高知大学",
    place: "くろしおアリーナ",
    date: "2021-01-17",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "163",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11043,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "高知県春季ジュニア",
  },
  {
    id: "164",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 23673,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "165",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 93407,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2012-01-14",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "166",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2602,
    swimmer1: "森",
    swimmer2: "圭祐",
    swimmer3: null,
    swimmer4: null,
    team: "中村高校",
    place: "ダイエープロビスフェニックス",
    date: "2013-03-30",
    meet: "全国JOC春季",
  },
  {
    id: "167",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 5505,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-02-15",
    meet: "高知県春季ジュニア",
  },
  {
    id: "168",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 11987,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-01-18",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "169",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 2877,
    swimmer1: "田渕",
    swimmer2: "寛大",
    swimmer3: null,
    swimmer4: null,
    team: "鹿屋体育大",
    place: "くろしおアリーナ",
    date: "2018-04-22",
    meet: "高知県春季",
  },
  {
    id: "170",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6097,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-03-21",
    meet: "全国JOC春季通信大会",
  },
  {
    id: "171",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13033,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-01-17",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "172",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2434,
    swimmer1: "西山",
    swimmer2: "隆詞",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2016-02-14",
    meet: "高知県春季ジュニアチャレンジ",
  },
  {
    id: "173",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5408,
    swimmer1: "西内",
    swimmer2: "匠",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-07-12",
    meet: "高知県SC夏季記録会",
  },
  {
    id: "174",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 11888,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2002-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "175",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12119,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2003-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "176",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 25301,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2003-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "177",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 9916,
    swimmer1: "湯口",
    swimmer2: "道端",
    swimmer3: "豊田",
    swimmer4: "小松",
    team: "高知大学",
    place: "アクアパレットまつやま",
    date: "2018-12-09",
    meet: "EHIME FEDERATION CUP",
  },
  {
    id: "178",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 20988,
    swimmer1: "丑本",
    swimmer2: "渋谷",
    swimmer3: "坂本",
    swimmer4: "矢野",
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "県春季ジュニア",
  },
  {
    id: "179",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 10907,
    swimmer1: "豊田",
    swimmer2: "湯口",
    swimmer3: "道端",
    swimmer4: "小松",
    team: "高知大学",
    place: "アクアパレットまつやま",
    date: "2018-12-09",
    meet: "EHIME FEDERATION CUP",
  },
  {
    id: "180",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 22890,
    swimmer1: "岩﨑",
    swimmer2: "田渕",
    swimmer3: "上田",
    swimmer4: "島内",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2014-07-06",
    meet: "高知県JOC予選会",
  },
  {
    id: "181",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2608,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2010-02-21",
    meet: "高知県A・AA級",
  },
  {
    id: "182",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5696,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-07-27",
    meet: "高知県JOC予選会",
  },
  {
    id: "183",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12193,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2011-02-27",
    meet: "高知県A・AA級",
  },
  {
    id: "184",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 25650,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2010-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "185",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 53783,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2010-02-14",
    meet: "高知県春季ジュニア",
  },
  {
    id: "186",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2820,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "187",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6071,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-02-26",
    meet: "高知県A・AA級",
  },
  {
    id: "188",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13219,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "アクアパレットまつやま",
    date: "2011-04-24",
    meet: "四国SC対抗",
  },
  {
    id: "189",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3256,
    swimmer1: "中城",
    swimmer2: "実弓",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-07-27",
    meet: "全国JOC予選会",
  },
  {
    id: "190",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6855,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "近畿大学",
    place: "秋葉山公園県民水泳場",
    date: "2021-12-19",
    meet: "関西学生冬季公認記録会",
  },
  {
    id: "191",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 14447,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "近畿大学",
    place: "秋葉山公園県民水泳場",
    date: "2021-12-19",
    meet: "関西学生冬季公認記録会",
  },
  {
    id: "192",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2759,
    swimmer1: "矢部",
    swimmer2: "瀬里香",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-02-16",
    meet: "高知県SC協会記録会",
  },
  {
    id: "193",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6123,
    swimmer1: "岩瀬",
    swimmer2: "夕楓",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "194",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 13300,
    swimmer1: "前野",
    swimmer2: "希和",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-07-12",
    meet: "高知県SC夏季記録会",
  },
  {
    id: "195",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 13554,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2018-01-06",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "196",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 28483,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "近畿大学",
    place: "秋葉山公園県民水泳場",
    date: "2020-12-05",
    meet: "関西学生冬季公認記録会",
  },
  {
    id: "197",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 10867,
    swimmer1: "矢部",
    swimmer2: "岩瀬",
    swimmer3: "西ノ内",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2019-12-08",
    meet: "EHIME FEDERATION CUP",
  },
  {
    id: "198",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 23538,
    swimmer1: "矢部",
    swimmer2: "西ノ内",
    swimmer3: "山下",
    swimmer4: "松木",
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2020-01-12",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "199",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 11941,
    swimmer1: "山下",
    swimmer2: "西ノ内",
    swimmer3: "岩瀬",
    swimmer4: "矢部",
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2019-12-08",
    meet: "EHIME FEDERATION CUP",
  },
  {
    id: "200",
    category: "高知県記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 25336,
    swimmer1: "矢部",
    swimmer2: "松木",
    swimmer3: "前野",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2019-01-12",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "201",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2526,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2022-01-09",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "202",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5427,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "203",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11930,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "204",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 26247,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "205",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 109526,
    swimmer1: "櫛田",
    swimmer2: "航大",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "高知県春季ジュニア",
  },
  {
    id: "206",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2824,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2022-01-09",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "207",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6291,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "208",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 14541,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "209",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3118,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2022-01-09",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "210",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6823,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "211",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 15475,
    swimmer1: "安原",
    swimmer2: "優輝",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2018-12-09",
    meet: "EHIME FEDERATIO NCUP",
  },
  {
    id: "212",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2611,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2022-01-09JSCA",
    meet: "新年フェスティバル",
  },
  {
    id: "213",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5981,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "214",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 13289,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "215",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 13455,
    swimmer1: "川田",
    swimmer2: "琉空斗",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-07-11",
    meet: "全国JOC夏季県予選",
  },
  {
    id: "216",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 29186,
    swimmer1: "三善",
    swimmer2: "大煌",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "217",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11358,
    swimmer1: "岡本",
    swimmer2: "坂本",
    swimmer3: "濱本",
    swimmer4: "高橋",
    team: "コナミ高知",
    place: "くろしおアリーナ",
    date: "2016-02-14",
    meet: "高知県春季ジュニア",
  },
  {
    id: "218",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12357,
    swimmer1: "南",
    swimmer2: "池田",
    swimmer3: "藤本",
    swimmer4: "谷",
    team: "高知県",
    place: "松山市コミュニティセンター",
    date: "1996-11-04",
    meet: "四国選手権",
  },
  {
    id: "219",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2726,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2011-01-15",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "220",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5943,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2011-02-27",
    meet: "高知県A・AA級",
  },
  {
    id: "221",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 13011,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2011-02-20",
    meet: "高知県春季ジュニア",
  },
  {
    id: "222",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 28168,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-02-26",
    meet: "高知県A・AA級",
  },
  {
    id: "223",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 3025,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2007-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "224",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6536,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2007-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "225",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 14425,
    swimmer1: "梅原",
    swimmer2: "千鈴",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-02-15",
    meet: "高知県春季ジュニア",
  },
  {
    id: "226",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3372,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2014-02-23",
    meet: "高知県A・AA級",
  },
  {
    id: "227",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7072,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "東京辰巳国際水泳場",
    date: "2014-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "228",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 15085,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2014-02-16",
    meet: "高知県春季ジュニア",
  },
  {
    id: "229",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2937,
    swimmer1: "森田",
    swimmer2: "紗矢",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-03-21",
    meet: "全国JOC春季通信大会",
  },
  {
    id: "230",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6405,
    swimmer1: "戸田",
    swimmer2: "千聖",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2010-02-14",
    meet: "高知県春季ジュニア",
  },
  {
    id: "231",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 14710,
    swimmer1: "前野",
    swimmer2: "希和",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2015-12-06",
    meet: "EHIME FEDERATION CUP",
  },
  {
    id: "232",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 14082,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2014-02-16",
    meet: "高知県春季ジュニア",
  },
  {
    id: "233",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 29569,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2014-02-16",
    meet: "高知県春季ジュニア",
  },
  {
    id: "234",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11565,
    swimmer1: "夏伐",
    swimmer2: "前田",
    swimmer3: "久保田",
    swimmer4: "渡辺",
    team: "ピープル高知",
    place: "くろしおアリーナ",
    date: "2002-02-24",
    meet: "高知県A・AA級",
  },
  {
    id: "235",
    category: "高知県学童記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12599,
    swimmer1: "梅原",
    swimmer2: "山本",
    swimmer3: "博田",
    swimmer4: "西山",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-02-22",
    meet: "高知県SC記録会",
  },
  {
    id: "236",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2409,
    swimmer1: "島内",
    swimmer2: "蓮人",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2013-02-24",
    meet: "高知県A・AA級",
  },
  {
    id: "237",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5319,
    swimmer1: "坂本",
    swimmer2: "昂太",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2019-02-17",
    meet: "高知県SC記録会",
  },
  {
    id: "238",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11425,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2015-01-11",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "239",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 23957,
    swimmer1: "松田",
    swimmer2: "悠成",
    swimmer3: null,
    swimmer4: null,
    team: "高知中",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "240",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 97980,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2010-01-16",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "241",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2705,
    swimmer1: "森圭",
    swimmer2: "祐",
    swimmer3: null,
    swimmer4: null,
    team: "中村SC",
    place: "くろしおアリーナ",
    date: "2011-02-27",
    meet: "高知県A・AA級",
  },
  {
    id: "242",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 5835,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2007-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "243",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 12549,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2007-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "244",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 2960,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2018-02-11",
    meet: "高知県春季ジュニア",
  },
  {
    id: "245",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6293,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2018-02-18",
    meet: "高知県SC記録会チャレンジ",
  },
  {
    id: "246",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13261,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "東京辰巳国際水泳場",
    date: "2018-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "247",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2517,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "ISC",
    place: "東京辰巳国際水泳場",
    date: "2014-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "248",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5523,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "ISC",
    place: "くろしおアリーナ",
    date: "2015-02-22",
    meet: "高知県SC記録会",
  },
  {
    id: "249",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 12193,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2000-03-30",
    meet: "全国JOC春季",
  },
  {
    id: "250",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12633,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "春野室内プール",
    date: "2000-02-27",
    meet: "高知県A・AA級",
  },
  {
    id: "251",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 26247,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "高知市体育館プール",
    date: "2000-01-10",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "252",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 10499,
    swimmer1: "平林",
    swimmer2: "谷",
    swimmer3: "竹内",
    swimmer4: "藤本",
    team: "高知県",
    place: "香川県立総合プール",
    date: "1997-11-23",
    meet: "四国選手権",
  },
  {
    id: "253",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 22271,
    swimmer1: "坂本",
    swimmer2: "寺井",
    swimmer3: "小松",
    swimmer4: "岡本",
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2018-07-08",
    meet: "全国JOC予選会",
  },
  {
    id: "254",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 11445,
    swimmer1: "藤本",
    swimmer2: "樋口",
    swimmer3: "松木",
    swimmer4: "三木",
    team: "高知県",
    place: "県民体育館プール",
    date: "1999-11-21",
    meet: "四国選手権",
  },
  {
    id: "255",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 23911,
    swimmer1: "野島",
    swimmer2: "安原",
    swimmer3: "小松",
    swimmer4: "岩瀬",
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2022-02-13",
    meet: "高知県春季ジュニア",
  },
  {
    id: "256",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2619,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "コナミ高知",
    place: "ダイエープロビスフェニックス",
    date: "2013-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "257",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5715,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "258",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12395,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2010-01-16",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "259",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 25650,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2010-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "260",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 53783,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2010-02-14",
    meet: "高知県春季ジュニア",
  },
  {
    id: "261",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2855,
    swimmer1: "西川",
    swimmer2: "雅世",
    swimmer3: null,
    swimmer4: null,
    team: "コナミ高知",
    place: "東京辰巳国際水泳場",
    date: "2014-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "262",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6131,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "東京辰巳国際水泳場",
    date: "2010-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "263",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13346,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2002-02-24",
    meet: "高知県A・AA級",
  },
  {
    id: "264",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3290,
    swimmer1: "澁谷",
    swimmer2: "桃子",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2010-02-14",
    meet: "高知県春季ジュニア",
  },
  {
    id: "265",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 7043,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2015-01-11",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "266",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 14779,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2016-05-08",
    meet: "四国SC対抗",
  },
  {
    id: "267",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2789,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2010-02-21",
    meet: "高知県A・AA級",
  },
  {
    id: "268",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6225,
    swimmer1: "戸田",
    swimmer2: "千聖",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "東京辰巳国際水泳場",
    date: "2012-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "269",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 13502,
    swimmer1: "佐々木",
    swimmer2: "り凡",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2001-07-30",
    meet: "高知県JO予選会",
  },
  {
    id: "270",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 13591,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2017-01-07",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "271",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 28745,
    swimmer1: "新野",
    swimmer2: "杏奈",
    swimmer3: null,
    swimmer4: null,
    team: "土佐塾中",
    place: "くろしおアリーナ",
    date: "2013-02-17",
    meet: "高知県春季ジュニア",
  },
  {
    id: "272",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11482,
    swimmer1: "國吉",
    swimmer2: "武田",
    swimmer3: "猪野",
    swimmer4: "山崎",
    team: "高知県",
    place: "香川県立総合プール",
    date: "1997-11-23",
    meet: "四国選手権",
  },
  {
    id: "273",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 24079,
    swimmer1: "秋森",
    swimmer2: "西ノ内",
    swimmer3: "野中",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "香川県立総合プール",
    date: "2018-02-25",
    meet: "香川県JO予選会",
  },
  {
    id: "274",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12492,
    swimmer1: "國吉",
    swimmer2: "森本",
    swimmer3: "堤",
    swimmer4: "武田",
    team: "高知県",
    place: "香川県立総合プール",
    date: "1997-11-23",
    meet: "四国選手権",
  },
  {
    id: "275",
    category: "高知県中学記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 25980,
    swimmer1: "山下",
    swimmer2: "秋森",
    swimmer3: "前野",
    swimmer4: "西ノ内",
    team: "ZEYO-ST",
    place: "香川県立総合プール",
    date: "2018-02-25",
    meet: "香川県JO予選会",
  },
  {
    id: "276",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "50m",
    time: 2364,
    swimmer1: "櫛田",
    swimmer2: "航大",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "277",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "100m",
    time: 5110,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "高知県春季ジュニア",
  },
  {
    id: "278",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "200m",
    time: 11043,
    swimmer1: "丑本",
    swimmer2: "知大",
    swimmer3: null,
    swimmer4: null,
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "高知県春季ジュニア",
  },
  {
    id: "279",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "400m",
    time: 23673,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "280",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "自由形",
    distance: "1500m",
    time: 93407,
    swimmer1: "西内",
    swimmer2: "司",
    swimmer3: null,
    swimmer4: null,
    team: "高知空港SS",
    place: "くろしおアリーナ",
    date: "2012-01-14",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "281",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2602,
    swimmer1: "森",
    swimmer2: "圭祐",
    swimmer3: null,
    swimmer4: null,
    team: "中村高",
    place: "ダイエープロビスフェニックス",
    date: "2013-03-30",
    meet: "全国JOC春季",
  },
  {
    id: "282",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "100m",
    time: 5505,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-02-15",
    meet: "高知県春季ジュニア",
  },
  {
    id: "283",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "背泳ぎ",
    distance: "200m",
    time: 11987,
    swimmer1: "伊藤",
    swimmer2: "克",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-01-18",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "284",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "50m",
    time: 2895,
    swimmer1: "田渕",
    swimmer2: "寛大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2015-02-22",
    meet: "高知県SC記録会",
  },
  {
    id: "285",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6097,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-03-21",
    meet: "全国JOC春季通信大会",
  },
  {
    id: "286",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "平泳ぎ",
    distance: "200m",
    time: 13033,
    swimmer1: "安原",
    swimmer2: "聖力",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2021-01-17",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "287",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "50m",
    time: 2446,
    swimmer1: "深原",
    swimmer2: "大誠",
    swimmer3: null,
    swimmer4: null,
    team: "ISC",
    place: "東京辰巳国際水泳場",
    date: "2017-03-29",
    meet: "全国JOC春季",
  },
  {
    id: "288",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "100m",
    time: 5437,
    swimmer1: "西内",
    swimmer2: "匠",
    swimmer3: null,
    swimmer4: null,
    team: "高知中央高",
    place: "くろしおアリーナ",
    date: "2010-02-21",
    meet: "高知県A・AA級",
  },
  {
    id: "289",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "バタフライ",
    distance: "200m",
    time: 11888,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2002-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "290",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "200m",
    time: 12119,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2003-03-28",
    meet: "全国JOC春季",
  },
  {
    id: "291",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "個人メドレー",
    distance: "400m",
    time: 25301,
    swimmer1: "藤本",
    swimmer2: "翔大",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "東京辰巳国際水泳場",
    date: "2003-03-27",
    meet: "全国JOC春季",
  },
  {
    id: "292",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 20988,
    swimmer1: "丑本",
    swimmer2: "渋谷",
    swimmer3: "坂本",
    swimmer4: "矢野",
    team: "NSP高知",
    place: "くろしおアリーナ",
    date: "2017-02-12",
    meet: "高知県春季ジュニア",
  },
  {
    id: "293",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "男子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 22890,
    swimmer1: "岩﨑",
    swimmer2: "田渕",
    swimmer3: "上田",
    swimmer4: "島内",
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2014-07-06",
    meet: "高知県JOC予選会",
  },
  {
    id: "294",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "50m",
    time: 2608,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2010-02-21",
    meet: "高知県A・AA級",
  },
  {
    id: "295",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "100m",
    time: 5696,
    swimmer1: "中川",
    swimmer2: "靖菜",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-07-27",
    meet: "高知県JOC予選会",
  },
  {
    id: "296",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "200m",
    time: 12193,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2011-02-27",
    meet: "高知県A・AA級",
  },
  {
    id: "297",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "400m",
    time: 25827,
    swimmer1: "早本",
    swimmer2: "吏沙",
    swimmer3: null,
    swimmer4: null,
    team: "KONAMI高知",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "298",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "自由形",
    distance: "800m",
    time: 54024,
    swimmer1: "上田",
    swimmer2: "鈴乃",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2016-05-07",
    meet: "四国SC対抗",
  },
  {
    id: "299",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "50m",
    time: 2820,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "300",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "100m",
    time: 6071,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-02-26",
    meet: "高知県A・AA級",
  },
  {
    id: "301",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "背泳ぎ",
    distance: "200m",
    time: 13219,
    swimmer1: "佐々木",
    swimmer2: "麻い",
    swimmer3: null,
    swimmer4: null,
    team: "JSS高知",
    place: "アクアパレットまつやま",
    date: "2011-04-24",
    meet: "四国SC対抗",
  },
  {
    id: "302",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "50m",
    time: 3256,
    swimmer1: "中城",
    swimmer2: "実弓",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "くろしおアリーナ",
    date: "2009-07-27",
    meet: "高知県JOC予選会",
  },
  {
    id: "303",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "100m",
    time: 6973,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2020-01-11",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "304",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "平泳ぎ",
    distance: "200m",
    time: 14895,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2020-01-12",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "305",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "50m",
    time: 2759,
    swimmer1: "矢部",
    swimmer2: "瀬里香",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-02-16",
    meet: "高知県SC協会記録会",
  },
  {
    id: "306",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "100m",
    time: 6123,
    swimmer1: "岩瀬",
    swimmer2: "夕楓",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2022-02-20",
    meet: "高知県SC記録会",
  },
  {
    id: "307",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "バタフライ",
    distance: "200m",
    time: 13300,
    swimmer1: "前野",
    swimmer2: "希和",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-07-12",
    meet: "高知県SC夏季記録会",
  },
  {
    id: "308",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "200m",
    time: 13554,
    swimmer1: "松木",
    swimmer2: "琴美",
    swimmer3: null,
    swimmer4: null,
    team: "ZEYO-ST",
    place: "アクアパレットまつやま",
    date: "2018-01-06",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "309",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "個人メドレー",
    distance: "400m",
    time: 28699,
    swimmer1: "山本",
    swimmer2: "礼羅",
    swimmer3: null,
    swimmer4: null,
    team: "みかづきSS",
    place: "アクアパレットまつやま",
    date: "2022-01-08",
    meet: "JSCA新年フェスティバル",
  },
  {
    id: "310",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×50m",
    time: 11293,
    swimmer1: "植野",
    swimmer2: "近森",
    swimmer3: "武田",
    swimmer4: "西森",
    team: "高知県",
    place: "県民体育館プール",
    date: "1999-11-21",
    meet: "四国選手権",
  },
  {
    id: "311",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "フリーリレー",
    distance: "4×100m",
    time: 23564,
    swimmer1: "川田",
    swimmer2: "森",
    swimmer3: "竹内",
    swimmer4: "佐々木",
    team: "JSS高知",
    place: "くろしおアリーナ",
    date: "2012-07-15",
    meet: "高知県JOC予選会",
  },
  {
    id: "312",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×50m",
    time: 12285,
    swimmer1: "國吉",
    swimmer2: "森本",
    swimmer3: "堤",
    swimmer4: "植野",
    team: "高知県",
    place: "県民体育館プール",
    date: "1999-11-21",
    meet: "四国選手権",
  },
  {
    id: "313",
    category: "高知県高校記録",
    poolsize: "短水路",
    sex: "女子",
    style: "メドレーリレー",
    distance: "4×100m",
    time: 25398,
    swimmer1: "矢部",
    swimmer2: "松木",
    swimmer3: "前野",
    swimmer4: "山下",
    team: "ZEYO-ST",
    place: "くろしおアリーナ",
    date: "2020-02-16",
    meet: "高知県SC協会記録会チャレンジ",
  },
];
